# Generated by Django 4.2.7 on 2024-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='signupAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNo', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=25)),
                ('zipcode', models.CharField(max_length=6)),
                ('otp', models.IntegerField()),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
