# Generated by Django 4.2.7 on 2024-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupaction',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
