# Generated by Django 4.2.7 on 2024-02-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_signupaction_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupaction',
            name='otp',
        ),
    ]
