# Generated by Django 4.2.7 on 2024-03-20 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('feedback_date', models.DateTimeField(default=datetime.datetime.today)),
                ('user_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signupaction')),
            ],
        ),
    ]
