# Generated by Django 4.2.7 on 2024-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
