# Generated by Django 4.2.7 on 2024-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='amc_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=40)),
                ('plan_description', models.TextField()),
                ('price', models.IntegerField()),
                ('service', models.BooleanField(default=True)),
                ('filter', models.BooleanField(default=False)),
                ('membrane', models.BooleanField(default=False)),
                ('electric_parts', models.BooleanField(default=False)),
                ('faulty_parts', models.BooleanField(default=False)),
            ],
        ),
    ]
