# Generated by Django 4.2.7 on 2024-02-21 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_signupaction_otp'),
        ('orders', '0004_amc_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='amc_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('amc_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.amc_plans')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signupaction')),
            ],
        ),
    ]
