# Generated by Django 4.2.7 on 2024-02-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_amc_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
