# Generated by Django 4.2.7 on 2024-02-21 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=50)),
                ('total_amount', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.datetime.today)),
                ('payment_status', models.BooleanField(default=False)),
                ('amc_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.amc_orders')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
