# Generated by Django 4.2.7 on 2024-02-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amc_plan',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='orders.amc_orders'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
