# Generated by Django 4.2.7 on 2024-02-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_amc_plan_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amc_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.amc_orders'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
