# Generated by Django 4.2.7 on 2024-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_payment_amc_plan_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
