# Generated by Django 4.2.7 on 2024-02-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc_plans',
            name='plan_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
