# Generated by Django 4.2.7 on 2024-02-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_cancelorder_orderdate_cancelorder_p_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cancelOrder',
        ),
    ]
