# Generated by Django 4.2.7 on 2024-02-26 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_signupaction_otp'),
        ('orders', '0016_delete_cancelorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('orderdate', models.CharField(default='', max_length=40)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('p_price', models.PositiveBigIntegerField(default=0)),
                ('paymentmode', models.CharField(default='Online', max_length=40)),
                ('reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signupaction')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
