# Generated by Django 4.2.7 on 2024-02-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cancelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='orderdate',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='p_price',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='qty',
        ),
    ]
