# Generated by Django 4.2.7 on 2024-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_cancelorder_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='order',
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='orderdate',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='p_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='paymentmode',
            field=models.CharField(default='Online', max_length=40),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
