# Generated by Django 4.2.7 on 2024-02-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_cancelorder_order_cancelorder_orderdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cancelOrder',
        ),
    ]
