# Generated by Django 4.2.7 on 2024-01-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
