# Generated by Django 4.2.7 on 2024-01-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.FileField(default=None, max_length=250, null=True, upload_to='product_images/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_category')),
            ],
        ),
    ]
