# Generated by Django 4.2.7 on 2024-01-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
